name: scijava-docs-ops
channels:
  - conda-forge
  - defaults
dependencies:
  - myst-nb
  - openjdk=11
  - plotly
  - sphinx=7.2
  - sphinx-copybutton
  - sphinx_rtd_theme

  - pip
  - pip:
      # NB: Needed for newer sphinx versions - see
      # https://github.com/thclark/sphinx-charts/issues/23
      - sphinxcontrib-jquery
      - sphinx-multiproject
      - readthedocs-sphinx-search
      - sphinx-tabs
      - sphinx_charts
